
baseURL = "https://example.org"

disableKinds = ["taxonomy", "term"]

[outputs]
home = ["HTML"]

[module]
[module.hugoVersion]
extended = true
min = "0.75.0"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss-v5"
[[module.imports]]
path="github.com/bep/hugo-dummy-content"